---
- name: Delete any previous DNS record in CloudFlare associated to {{ cloudflare_hostname }}
  cloudflare_domain:
    state:  absent
    name: "{{ cloudflare_hostname | mandatory }}"
    zone: "{{ cloudflare_zone | mandatory }}"
    type: "{{ cloudflare_record_type | mandatory }}"
    content: "*"
    email: "{{ cloudflare_api_email | mandatory }}"
    token: "{{ cloudflare_api_token | mandatory }}"
  delegate_to: localhost

- name: Create DNS record in CloudFlare
  cloudflare_domain:
    state:  present
    name: "{{ cloudflare_hostname | mandatory }}"
    zone: "{{ cloudflare_zone | mandatory }}"
    type: "{{ cloudflare_record_type | mandatory }}"
    content: "{{ cloudflare_record_content | mandatory }}"
    email: "{{ cloudflare_api_email | mandatory }}"
    token: "{{ cloudflare_api_token | mandatory }}"
  delegate_to: localhost
...
