---
- include_vars: groups.yml
  when: user_groups_environment is defined

- name: Create the groups for the environment
  group:
    name:   "{{ item.name }}"
    gid:    "{{ item.gid }}"
    state:  present
  when: user_groups_environment is defined
  with_items: "{{user_groups_environment|default}}"
  become: true

...
