---
#- include: server-name.yml

# - hosts: all:!localhost
#   gather_facts: false
#   roles:
#     - { role: provisioning }

- name: Process Hostname configuration
  include: hostname.yml

- name: Process Environement Groups configurations
  include: groups.yml

- name: Process Sudoers configurations
  include: sudoers.yml
  when: update_sudoers is defined and update_sudoers

...
