---
#- include: server-name.yml

# - hosts: all:!localhost
#   gather_facts: false
#   roles:
#     - { role: provisioning }

- include: hostname.yml
- include: groups.yml

- include: cloudflare.yml
  when: cloudflare_zone is defined

- include: sudoers.yml
  when: update_sudoers is defined

...
