---
- name: Add the groups to sudoers.d
  template: >
    src='sudo-group.j2'
    dest="/etc/sudoers.d/{{ item.filename }}"
    owner='root'
    group='root'
    mode='0440'
    validate='visudo -cf %s'
  when: "update_sudoers is defined and update_sudoers"
  with_items: "{{sudoers_groups|default}}"
  become: true
...
